dovecot_config_version = 2.4.0
dovecot_storage_version = 2.4.0

!include_try /usr/share/dovecot/protocols.d/*.protocol
protocols = imap lmtp
listen = *, [::]
!include conf.d/*.conf
!include_try /var/mail/dovecot/conf.d/*.conf
