mail_driver = maildir
mail_path = /var/mail/vhosts/%{user | domain}/%{user | username}/{{ .VMAIL_SUBDIR }}
maildir_stat_dirs = yes

namespace inbox {
  inbox = yes
}

mail_uid = {{ .VMAILUID }}
mail_gid = {{ .VMAILGID }}

first_valid_uid = {{ .VMAILUID }}
last_valid_uid = {{ .VMAILUID }}

mail_privileged_group = vmail

mail_plugins {
  quota = yes
  mail_compress = yes
{{ if ne .DBDRIVER "ldap" }}
  quota_clone = yes
{{ end }}
}

# Compression of saved mails (replaces the 2.3 zlib plugin)
mail_compress_write_method = gz
compress_gz_level = 6
