ssl = required
ssl_server_cert_file = {{ .FULLCHAIN }}
ssl_server_key_file = {{ .KEYFILE }}
ssl_min_protocol = TLSv1.2
# PFS only and disallow non-ECC based DH algorithms
ssl_cipher_list = EECDH+AES:EDH+AES+aRSA:!DH
ssl_server_prefer_ciphers = server
