protocol lmtp {

  postmaster_address = postmaster@{{ .DOMAIN }}

  # See 20-imap.conf: this block replaces the global mail_plugins rather than
  # extending it.
  mail_plugins {
    quota = yes
    mail_compress = yes
{{ if ne .DBDRIVER "ldap" }}
    quota_clone = yes
{{ end }}
    sieve = yes
  }

}
